//
//  AssetDragPayload.swift
//  AtelierRefs
//
//  009 · N3 — the ONE drag payload shared by in-grid reorder, the Unsorted stack
//  row, the drop rail, and (future) the gallery. Carries the dragged asset ids
//  PLUS their source collection, so a drop can tell a same-collection reorder
//  from a cross-collection move without guessing. Replaces the old bare-UUID
//  `String` payload everywhere.
//
//  The custom `UTType` is BOTH declared in `Info.plist`
//  (`UTExportedTypeDeclarations`, conforming to `public.data`) AND mirrored here
//  via `UTType(exportedAs:)`. The Info.plist declaration is load-bearing: without
//  it the OS doesn't recognize the identifier at a drop destination, so every
//  drag (reorder / stack-move / rail-move) shows an invalid cursor and snaps back.
//

import AppKit
import AtelierCore
import CoreTransferable
import Foundation
import UniformTypeIdentifiers

extension UTType {
    /// The app-private drag identifier for a set of asset ids + their source.
    static let assetIDs = UTType(exportedAs: "com.ref-atelier.asset-ids")
}

/// A dragged set of assets and where they came from (009 · N3). `Codable` for the
/// transfer representation; `Equatable` for tests.
struct AssetDragPayload: Codable, Equatable, Transferable {
    /// The dragged assets, in the source's feed order.
    var assetIDs: [UUID]
    /// The collection the drag started from — lets a drop distinguish a
    /// same-collection reorder from a cross-collection move, and enforce the
    /// `from == to` no-op.
    var sourceCollectionID: UUID

    static var transferRepresentation: some TransferRepresentation {
        CodableRepresentation(contentType: .assetIDs)
    }
}

// MARK: - NSPasteboard bridge (036 §4 A3 — byte-compatible with the SwiftUI drag)

extension AssetDragPayload {
    /// The pasteboard type the AppKit drag writes under — the SAME identifier the
    /// `.assetIDs` `UTType` (and therefore the SwiftUI `CodableRepresentation`)
    /// uses, so a drag started on the AppKit grid lands on the still-SwiftUI drop
    /// rail / stack row / Spaces exactly as the SwiftUI `.draggable` did.
    static let pasteboardType = NSPasteboard.PasteboardType(UTType.assetIDs.identifier)

    /// The wire bytes for this payload — plain `JSONEncoder`, which is precisely
    /// what SwiftUI's `CodableRepresentation(contentType:)` serializes (036 §4 A3).
    /// This IS the interop contract: `AssetDragPayloadTests` pins that these bytes
    /// decode back through the same `Codable` form the SwiftUI drop targets use, so
    /// a drift here silently breaks drag-to-rail and the test catches it.
    func pasteboardData() throws -> Data { try JSONEncoder().encode(self) }

    /// An `NSPasteboardItem` carrying this payload's JSON under `.pasteboardType`,
    /// for `NSDraggingItem(pasteboardWriter:)`. `nil` only if encoding fails (it
    /// cannot for this value type).
    func makePasteboardItem() -> NSPasteboardItem? {
        guard let data = try? pasteboardData() else { return nil }
        let item = NSPasteboardItem()
        item.setData(data, forType: Self.pasteboardType)
        return item
    }

    /// Decode a payload from a drop's pasteboard bytes — the inverse of
    /// ``pasteboardData()``, used by the AppKit cell-drop delegate.
    static func decode(from data: Data) -> AssetDragPayload? {
        try? JSONDecoder().decode(AssetDragPayload.self, from: data)
    }

    /// A payload that marks a drag as INTERNAL without granting it any drop
    /// semantics: `routeDrop` rejects an empty asset list at every target, while
    /// the collection pane's import guard still sees the `.assetIDs` type and
    /// refuses to re-ingest the app's own file. Used by the detail hosts that
    /// have no collection context (library search, a Space board).
    static let internalMarker = AssetDragPayload(
        assetIDs: [],
        // The nil UUID — a fixed, impossible collection id (never generated by
        // `UUID()`), so the marker can't collide with a real source.
        sourceCollectionID: UUID(uuid: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)))

    /// Read the payload straight off the system DRAG pasteboard, if the drag in
    /// flight carries one.
    ///
    /// This is the ONE reliable read for an AppKit-originated drag: when the
    /// dragging item is an `NSFilePromiseProvider` (every media drag since 011
    /// drag-out), SwiftUI's bridged `NSItemProvider` exposes NO type identifiers
    /// at all (proven by the 193 diagnostics — `registeredTypeIdentifiers == []`),
    /// so a provider-based read finds nothing even though the `.assetIDs` bytes
    /// sit right on the drag pasteboard. Outside a drag this returns `nil` (the
    /// drag pasteboard holds the LAST drag's leftovers only until the next one
    /// starts; a stale payload here is unreachable because `.onDrop` closures
    /// only run mid-drag).
    static func fromDragPasteboard() -> AssetDragPayload? {
        guard let data = NSPasteboard(name: .drag).data(forType: Self.pasteboardType) else {
            return nil
        }
        return decode(from: data)
    }

    /// The drop-target entry point shared by the drop rail and the Unsorted stack
    /// cards: the drag pasteboard first (AppKit grid drags — promise-shaped or
    /// plain), then the provider bridge (a SwiftUI-native drag whose provider DOES
    /// carry `.assetIDs`). Returns whether a payload was found — the `.onDrop`
    /// accept result. `completion` runs on the main queue: synchronously for the
    /// pasteboard path, later for the async provider path.
    @discardableResult
    static func fromDrop(
        _ providers: [NSItemProvider], completion: @escaping (AssetDragPayload) -> Void
    ) -> Bool {
        if let payload = fromDragPasteboard() {
            completion(payload)
            return true
        }
        return loadFirst(from: providers, completion: completion)
    }

    /// Load the first `AssetDragPayload` from a SwiftUI `.onDrop` provider list —
    /// the FALLBACK half of ``fromDrop(_:completion:)``, only useful for drags
    /// whose `NSItemProvider` actually registers `.assetIDs` (a SwiftUI-native
    /// drag source; an AppKit promise drag's bridged provider registers nothing).
    /// Item providers load asynchronously, so `completion` runs later on the main
    /// queue; the return value is whether a matching provider was present.
    @discardableResult
    static func loadFirst(
        from providers: [NSItemProvider], completion: @escaping (AssetDragPayload) -> Void
    ) -> Bool {
        guard let provider = providers.first(where: {
            $0.hasItemConformingToTypeIdentifier(UTType.assetIDs.identifier)
        }) else { return false }
        provider.loadDataRepresentation(
            forTypeIdentifier: UTType.assetIDs.identifier
        ) { data, _ in
            guard let data, let payload = decode(from: data) else { return }
            DispatchQueue.main.async { completion(payload) }
        }
        return true
    }
}
