// The two KEY rules that the sanitizer and its audit must agree on, in one place.
//
// Everything about sanitizing a capture is key-INDEPENDENT except a short list of rules
// where shape provably cannot decide (see sanitize-capture.js). Two of those rules are
// also the audit's business — one says "always replace this", the other says "never
// replace this" — and the audit was silently disagreeing with both:
//
//   · `creativemints`, `framer`, `figma` and `awwwards` are X handles AND bare lowercase
//     words, so the audit's `^[a-z]+$` rule reported every one as a STRUCTURAL survivor.
//   · `TimelineTimelineItem` is a GraphQL discriminator the sweep keeps verbatim, and the
//     audit had no rule for it at all, so keeping it correctly would have read as a leak.
//
// A private copy in each file is exactly how a fixture and the check on it drift apart —
// the same reason `isTransformDirective` is imported rather than respelled. This module
// holds NO logic and reads no files, so importing it can never run a sweep.

/** Keys whose string values name a PERSON: handles, display names, bios, artists.
 *
 * The sanitizer collects these wherever they appear and then replaces every occurrence of
 * the collected VALUE anywhere in the document; the audit refuses to excuse a survivor
 * that arrived under one, whatever its shape.
 *
 * `screen_name` is X's handle and its absence was the loudest gap 498 found: the
 * 2026-09-14 thread capture carries 65 distinct real ones (plus 13 under
 * `in_reply_to_screen_name`, which the unanchored alternative also covers) and not one was
 * ever replaced. `liker` is for IG's `top_likers`, a bare ARRAY OF HANDLES with no
 * identity-ish key on any leaf. `display_artist` is IG's track artist — `Cassie`, `Cielo`
 * and `d4vd` are people. `author_name` was missing once and leaked `mariosworld343`;
 * `site_name` names the source brand of a pin. `nick_?name` covers BOTH of rednote's
 * spellings — the board feed says `nick_name`, note detail says `nickname` (098 D6).
 *
 * Collection is broad on purpose: a false positive costs one synthetic string, a false
 * negative is a leak. */
export const IDENTITY_KEY =
  /username|screen_name|full_name|biography|^name$|nick_?name|profile_grid|owner_name|author_name|site_name|creator|pinner|liker|display_artist/i;

/** Keys holding the response envelope's TYPE DISCRIMINATOR, which is kept VERBATIM.
 *
 * X's is PascalCase and multi-word — `entryType: "TimelineTimelineItem"`, `__typename:
 * "TweetWithVisibilityResults"`, `cursorType: "ShowMore"` — and `bulk-twitter.js` compares
 * them to string literals, so a sanitized value parses to zero tweets. It is drawn by KEY
 * and not by shape because shape cannot do it: `TimelineTweet`, `SelfThread` and
 * `HighQuality` are the same PascalCase as `JayBorda`, `LeeScarfe` and `RasmusNielsen`,
 * which are people, and a value rule wide enough to keep the first three is an amnesty on
 * the last three. A `__typename` is machine-generated by construction — nothing a person
 * writes can land there. Across every capture in `resources/` these keys hold 30 distinct
 * values and every one is an envelope discriminator.
 *
 * `Type$` is deliberately capital-T: `media_type`, `content_type` and `capture_type` are
 * NOT shielded — a mime type reaches the audit's structural list on its own merits, and
 * IG's `media_type` is a number. */
export const SCHEMA_KEY = /^__typename$|Type$|^type$/;
